### ISSUE TITLE
Implementation of Huffman Coding in java.

### ISSUE THREAD

**Issue by Faizansayeed28** [CodeNerve/Let-Us-Java#150]
Huffman coding is a lossless data compression algorithm. The idea is to assign variable-length codes to input characters, lengths of the assigned codes are based on the frequencies of corresponding characters. The most frequent character gets the smallest code and the least frequent character gets the largest code.

**Comment by Faizansayeed28** [comment]
I want to work on this issue @Pradyuman7 .please assign this to me.

**Comment by Pradyuman7** [comment]
Let's not make issues for new implementation, please use the issue #3
