### ISSUE TITLE
Duplicate Code for GoldMine Problem

### ISSUE THREAD

**Issue by samratpodder** [CodeNerve/Let-Us-Java#338]
There are two similar solutions for the same problem. One is under the Dynamic Programming topic folder and another is in a standalone GoldMine Problem Folder.

**Comment by Rohans-7** [comment]
Hey can you please assign this issue to me. It will be really good first issue for me as a beginner. 
Thank you !!!

**Comment by Pradyuman7** [comment]
There's quite a lot of duplicate code in the repository now, so I have created #347. Closing this issue in favour of that. Thanks for bringing this to attention
